name: Deploy WordPress Plugin

on:
  push:
    branches: [main] # or any branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to SFTP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          source: "./*" # Adjust the path to your plugin directory
          target: "/home/ologybrewing/website/wp-content/plugins/ology-custom" # The target directory on your server
